services:
  otel-collector:
    # image: otel/opentelemetry-collector:0.107.0
    image: otel/opentelemetry-collector-contrib:0.107.0
    # restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otelc-config.yaml:/etc/otel-collector-config.yaml
    # All the ports are visible.
    network_mode: "host"
    environment:
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
