apiVersion: 1
foo:
  - bar: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://caddy:3100
    jsonData:
      derivedFields:
        - datasourceName: Tempo
          datasourceUid: Tempo
          matcherType: label
          matcherRegex: trace_id
          name: traceID
          url: $${__value.raw}
    secureJsonData:
      httpHeaderValue1: "lokilocal"
  - name: Mimir
    type: prometheus
    url: http://caddy:3200/prometheus
    secureJsonData:
      httpHeaderValue1: "mimirlocal"
  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://caddy:3300
    jsonData:
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: 'Mimir'
      tracesToLogsV2:
        datasourceUid: Loki
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "+1m"
        # Tags that must exist on every span.
        # TODO: Insert wiht some kind of global span middleware?
        # tags: [{key: "service_name", value: "service_name"}]
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{service_name=~".+"} | trace_id=`$${__span.traceId}`'
