# https://grafana.com/docs/loki/latest/
target: all

auth_enabled: false

server:
  http_listen_port: 3100
  http_server_read_timeout: 10m
  http_server_write_timeout: 10m
  http_server_idle_timeout: 10m
  log_level: warn
memberlist:
  join_members:
    - loki:7946
query_range:
  cache_results: true
limits_config:
  split_queries_by_interval: 10m
schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h
common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: s3key
      secret_access_key: ${S3_ACCESS_KEY}
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist
ruler:
  storage:
    s3:
      bucketnames: loki-ruler
