# https://grafana.com/docs/mimir/latest/configure/configuration-parameters/
target: all,alertmanager,overrides-exporter

multitenancy_enabled: false

server:
  http_listen_port: 8080
  grpc_listen_port: 9095
  http_server_read_timeout: 10m
  http_server_write_timeout: 10m
  http_server_idle_timeout: 10m
  log_level: warn
memberlist:
  join_members:
    [mimir:7946]
common:
  storage:
    backend: s3
    s3:
      endpoint: minio:9000
      insecure: true
      access_key_id: s3key
      secret_access_key: s3secret
      bucket_name: mimir-data
alertmanager:
  external_url: http://localhost:9009/alertmanager
blocks_storage:
  storage_prefix: blocks
ruler_storage:
  storage_prefix: ruler
alertmanager_storage:
  storage_prefix: alertmanager
