server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: positions.yaml # This location needs to be writeable by Promtail.

clients:
  - url: http://caddy:3100/loki/api/v1/push

scrape_configs:
  - job_name: prometheus_scrape
    # docker_sd_configs:
    #   - host: unix:///var/run/docker.sock
    #     refresh_interval: 5s
    #     filters:
    #       - name: label
    #         values: ["logging=promtail"]
    # relabel_configs:
    #   - source_labels: ['__meta_docker_container_name']
    #     regex: '/(.*)'
    #     target_label: 'container'
    static_configs:
    - targets:
        - localhost
      labels:
        job: containerlogs
        __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
    - json:
        expressions:
          stream: stream
          attrs: attrs
          tag: attrs.tag
    - regex:
        expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
        source: "tag"
    - labels:
        tag:
        stream:
        image_name:
        container_name:
        image_id:
        container_id:
