server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: positions.yaml # This location needs to be writeable by Promtail.

clients:
  - url: http://gatewayloki:3100/loki/api/v1/push
    tenant_id: lokilocal

scrape_configs:
  - job_name: prometheus_scrape # Can have
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: [prometheus] # Scraps the logs of this container name
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
